name: mole
version: '0.1'
summary: IOT interactive server
description: >
  Server that store data from esp32 (humidity and temperature)
  json provided

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  go:
    source-tag: go1.7.5
  mole:
    plugin: go
    go-importpath: gitlab.com/wolfheimrick/mole
    source: https://gitlab.com/wolfheimrick/mole.git
    source-type: git

apps:
  mole:
    command: mole
